[package]
name = "pstd"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
dashmap = { version = "5.5", features = ["rayon", "serde"] }
flume = { version = "0.11", features = ["async", "select"] }
futures-lite = "2.3"
log = "0.4"
parking_lot = "0.12"
rand = { version = "0.8", features = ["log"] }
rayon = "1.8"
serde = "1.0"
serde_json = "1.0"