[package]
name = "pstd"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "*"
chrono = { version = "*", features = ["serde"] }
closure = "*"
flume = { version = "*", features = ["async", "select"] }
futures = "*"
log = "*"
parking_lot = "*"
rand = { version = "*", features = ["log"] }
rayon = "*"
scc = { version = "*", features = ["serde"] }