[package]
name = "pstd"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "*"
dashmap = { version = "*", features = ["rayon", "serde"] }
flume = { version = "*", features = ["async", "select"] }
futures-lite = "*"
log = "*"
parking_lot = "*"
rand = { version = "*", features = ["log"] }
rayon = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
